version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.1
    environment:
      - xpack.monitoring.elasticsearch.hosts=http://es01:9200
    volumes:
      - ./docker-configs/logstash/pipeline/:/usr/share/logstash/pipeline/
    ports:
      - 45600:45600

  kib01:
    image: docker.elastic.co/kibana/kibana:7.6.1
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200

volumes:
  data01:
